### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Octolus** [christophetd/CloudFlair#12]
It seems like it's nearly easier to go to their website, search domain you want.

Then grab an IP and send curl host header to identify if that's the right one. 

Add functionality so it can do that too? Instead of only certs. My domains IP is on the site but it cant find it using this tool

**Comment by christophetd** [comment]
CloudFlair already does that: https://github.com/christophetd/CloudFlair/blob/master/cloudflair.py#L104-L111

Is that what you meant?

**Comment by christophetd** [comment]
Closing this for now, feel free to reopen if needed.
