### ISSUE TITLE
secret key 

### ISSUE THREAD

**Issue by gujjuboy10x00** [christophetd/CloudFlair#15]
Is there any way that i can add censys secret key in my github (private) , so no need to enter manually in CLI

**Comment by christophetd** [comment]
The best way IMO is to add the environment variables to your `~/.bashrc`.

```bash
$ echo "export CENSYS_API_ID=your-id" >> ~/.bashrc
$ echo "export CENSYS_API_SECRET=your-secret" >> ~/.bashrc
$ source ~/.bashrc
$ python cloudflair.py myvulnerable.site # No need to manually define the environment variables or to pass CLI parameters
```

**Comment by christophetd** [comment]
Otherwise yes, you could hardcode these values [in the code](https://github.com/christophetd/CloudFlair/blob/master/cloudflair.py#L151-L152), but I would advise against it. Especially, you wouldn't be able to pull future updates, as you'd be getting a merge conflict from git.

**Comment by christophetd** [comment]
Closing for now, but feel free to reopen if you have further questions!
