### ISSUE TITLE
Issue no module

### ISSUE THREAD

**Issue by joannadennis** [christophetd/CloudFlair#18]
Traceback (most recent call last):
  File "cloudflair.py", line 3, in <module>
    import dns_utils
  File "/root/cloudflair/dns_utils.py", line 1, in <module>
    import dns.resolver
ImportError: No module named dns.resolver

**Comment by christophetd** [comment]
What command did you run? Did you launch `pip install -r requirements.txt` as instructed before?

**Comment by joannadennis** [comment]
done install pip python and run pip install -r requirements.txt. 

Thank you christophetd
