### ISSUE TITLE
Throws exception when page content isn't retrieved

### ISSUE THREAD

**Issue by eur0pa** [christophetd/CloudFlair#19]
https://github.com/christophetd/CloudFlair/blob/65df78f63188880513a9792a7749e140ea203216/cloudflair.py#L127

This needs to be enclosed in a `try / except` block to avoid throwing an uncaught exception when the page content isn't retrieved for some reason.

**Comment by christophetd** [comment]
Good point. PRs are welcome, otherwise I'll try to take care as soon as I have a moment. 

Thanks for reporting!

**Comment by christophetd** [comment]
Fixed with #26
