### ISSUE TITLE
error

### ISSUE THREAD

**Issue by estrang09** [christophetd/CloudFlair#22]
i use python 3.6
python3 cloudflair.py mytarget.tld
[*] Retrieving Cloudflare IP ranges from https://www.cloudflare.com/ips-v4
Traceback (most recent call last):
  File "cloudflair.py", line 13, in <module>
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
AttributeError: 'module' object has no attribute 'disable_warnings'

**Comment by christophetd** [comment]
Can you try to run `pip install --upgrade  requests`, and then cloudflair again?
