### ISSUE TITLE
No Module named dns

### ISSUE THREAD

**Issue by dzhenway** [christophetd/CloudFlair#25]
cloudflair.py evil.com
Traceback (most recent call last):
  File "C:\Python3\CloudFlair-master\cloudflair.py", line 3, in <module>
    import dns_utils
  File "C:\Python3\CloudFlair-master\dns_utils.py", line 1, in <module>
    import dns.resolver
ModuleNotFoundError: No module named 'dns'

**Comment by codingo** [comment]
Before running you need to install requirements, you can do this by cloning the repository and then running:

```
pip install -r requirements.txt
```

You can find this and other setup instructions on the README.me of this repository (https://github.com/christophetd/CloudFlair)
