### ISSUE TITLE
No module named DNS.resolver

### ISSUE THREAD

**Issue by jmmiller60601** [christophetd/CloudFlair#28]
After running `pip install -r requirements.txt` and then trying to run the script, got the following. 

`File "cloudflair.py", line 3, in <module>
    import dns_utils
  File "/Users/[redacted]/cloudflair/dns_utils.py", line 1, in <module>
    import dns.resolver
ImportError: No module named dns.resolver`

**Comment by christophetd** [comment]
Which version of Python are you running?

If you don't manage to install dnspython using pip, I'd suggest trying `pip install git+https://github.com/rthalley/dnspython`

**Comment by jmmiller60601** [comment]
Python 2.7.10

I tried install DNSpython before submitting the ticket and that didn’t fix the issue.

**Comment by jmmiller60601** [comment]
I also tried installing it via Anaconda instead of pip and I'm still getting the same error.

**Comment by jmmiller60601** [comment]
Not sure what changed but was able to get it working.

**Comment by christophetd** [comment]
Amazing!
