### ISSUE TITLE
https://... responded with an unexpected HTTP status code 403

### ISSUE THREAD

**Issue by rrhg** [christophetd/CloudFlair#29]
...
[*] Testing candidate origin servers
[*] Retrieving target homepage at https://....com
[-] https://....com responded with an unexpected HTTP status code 403

Is Cloudflare detecting your tool ? 
I receive the same response when using curl.
But visiting the site from the browser works fine.
I'm running it with docker, if it makes any difference.

**Comment by christophetd** [comment]
Most likely related to #14, I assume the initial request is blocked because of the default Python requests user-agent.

**Comment by christophetd** [comment]
Fixed this in #30. Could you try again and let me know if that solves your issue?

**Comment by rrhg** [comment]
It gave me same 403 response. 
This the command I'm running.
sudo docker run --rm -e CENSYS_API_ID=mykey -e CENSYS_API_SECRET=mysecret christophetd/cloudflair awebsite.com

**Comment by rrhg** [comment]
Now it worked!.
