### ISSUE TITLE
File "cloudflair.py", line 7, in <module>

### ISSUE THREAD

**Issue by niemant** [christophetd/CloudFlair#37]
Hello,
I already installed the requirements and are ok but, when i run it as follows it get an error:

**python cloudflair.py www.website.com
[*] Retrieving Cloudflare IP ranges from https://www.cloudflare.com/ips-v4
Traceback (most recent call last):
  File "cloudflair.py", line 7, in <module>
    import censys_search
  File "/root/Scripts/CloudFlare/CloudFlair/censys_search.py", line 1, in <module>
    import censys.certificates
ImportError: No module named censys.certificates**

Regards.

**Comment by christophetd** [comment]
How did you run the pip install? What version of Python do you have? Try putting everything in a venv:

```
cd CloudFlair
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python cloudflair.py www.website.com
```

**Comment by niemant** [comment]
Still getting errors
![screen](https://user-images.githubusercontent.com/20712470/84546830-91f6b780-acd8-11ea-9469-d16e3fe6a5eb.png)

**Comment by niemant** [comment]
Python 3.8.3

I used pip the following way:
pip install -r requirements.txt

regards

**Comment by christophetd** [comment]
I updated the instructions in the README. Can you try the following and confirm it works fine?

```
cd cloudflair
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python cloudflair.py google.com
```

**Comment by christophetd** [comment]
Assuming it works now, feel free to reopen if needed

**Comment by christophetd** [comment]
What errors do you have, and what commands did you type precisely?

**Comment by Lulztigre** [comment]
i did the usual
python cloudflair.py target
the error says

ModuleNotFoundError: No Module Named 'censys.common'

**Comment by christophetd** [comment]
Did you install dependencies? `pip install -r requirements.txt`

**Comment by Lulztigre** [comment]
Yes, I did.

**Comment by christophetd** [comment]
Sorry but the instructions are working from my side. Try with a venv?

```
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
```

**Comment by Lulztigre** [comment]
Ok, I'll check it out.

**Comment by Lulztigre** [comment]
hello ,

sorry for not getting back to you, this totally worked fine, thank you.
