### ISSUE TITLE
CloudFlair - censys.CensysException: 400 (max_results): Only the first 1,000 search results are available

### ISSUE THREAD

**Issue by thealtener** [christophetd/CloudFlair#38]
if the censys account was non-commercial then a modification of
censys_search.py: line 30
        hosts_search_results = censys_hosts.search(hosts_query)
must be modified to
        hosts_search_results = censys_hosts.search(hosts_query,max_records=1000)

Cheers!

**Comment by christophetd** [comment]
Should be fixed in https://github.com/christophetd/CloudFlair/pull/51
