### ISSUE TITLE
Extract hosts not limited to CloudFlare

### ISSUE THREAD

**Issue by madaratech** [christophetd/CloudFlair#4]
Hi @christophetd!

This is good work, and great projection as well, while using I have noticed it uses certificate to extract hostname, but limited to host using Cloudflare which make sense here as per project, but it would be nice if we can extract all host for any given domain as well (it might be new project) or if you like to add into this only, what you think about it?

**Comment by christophetd** [comment]
I'm not sure I understand what your suggestion is. The goal of this tool is to help finding misconfigured origins behind Cloudflare, not to enumerate subdomains of a domain name (see [here](https://github.com/christophetd/censys-subdomain-finder) for that).

**Comment by madaratech** [comment]
Hi @christophetd, 

Yes, suggestion is unrelated to this tool, and I saw [this as well](https://github.com/christophetd/censys-subdomain-finder) , where it fetch all the subdomain using certificate and my above suggestion was for fetching all the HOST which sharing same certificate.   

do let me know if I'm making any sense here? or will close this out.

**Comment by christophetd** [comment]
Websites subscribed to the Cloudflare free plan indeed [share](https://support.cloudflare.com/hc/en-us/articles/203349264-Are-Cloudflare-s-SSL-certificates-shared-or-dedicated-) the same SSL certificate with several other websites. If I understood correctly, your idea would be to have a tool to find which websites are sharing a certificate with a specific website?
