### ISSUE TITLE
[Feature] Add favicon check

### ISSUE THREAD

**Issue by ctrlsam** [christophetd/CloudFlair#41]
As seen in https://github.com/pielco11/fav-up, it is possible to get a servers real IP using the hash of a fav-icon.
Perhaps it would be possible to implement something like this using the current API.

**Comment by christophetd** [comment]
Sounds like an interesting idea, but CloudFlair's goal is to implement a specific Cloudflare bypass method, so I would rather leave other tools like fav-up do the work.

Thanks for the suggestion!
