### ISSUE TITLE
SyntaxWarning error

### ISSUE THREAD

**Issue by GiangTieuDau** [christophetd/CloudFlair#42]
Hi Chris,

I am using the latest Kali 2020.4
My current python2 is 2.7.18 and python3 is 3.8.6U* 
I did run the exact command as the instruction
But when I run the command "python cloudflair.py <domain>"
And the error comes

File "cloudflair.py", line 3, in
import dns_utils
File "/home/kali/Desktop/cloudflair/dns_utils.py", line 1, in
import dns.resolver
ImportError: No module named 'dns'

Then I tried to run the command "python3 cloudflair.py <domain>"
It works but still got error

![image](https://user-images.githubusercontent.com/27785970/101400086-f9499900-3902-11eb-9813-2dc0ce008412.png)

I am wondering is SyntaxWarning error in line 46, 55, 157 affect the process as well as the result?
How to fix it?

**Comment by christophetd** [comment]
You likely forgot to install requirements: `pip install -r requirements.txt`

Will keep the issue open to track the syntax error

**Comment by christophetd** [comment]
Should be fixed by #43
