### ISSUE TITLE
ImportError: No module named dns.resolver    

### ISSUE THREAD

**Issue by airline12138** [christophetd/CloudFlair#45]
When i was running the 'python cloudflair.py url', the python printed this result:ImportError: No module named dns.resolver
What can i do next?

**Comment by airline12138** [comment]
It only appears on Debian system, and centos has not encountered this problem

**Comment by christophetd** [comment]
Have you installed dependencies running `pip install -r requirements.txt`?

**Comment by vignesh9600** [comment]
yes even after installing the dependencies using ` pip install -r requirements.txt` it shows the same error

**Comment by christophetd** [comment]
Can you provide your pip and Python versions?

**Comment by vignesh9600** [comment]
pip version `pip 21.2.4`
python version `Python 2.7.16`

**Comment by christophetd** [comment]
Can you try with Python 3.5?

**Comment by vignesh9600** [comment]
even after using python 3.5 it doesn't seem to work

**Comment by airline12138** [comment]
> Have you installed dependencies running `pip install -r requirements.txt`?

Of course. I tried to run it again and again,but running it isn't usful

**Comment by airline12138** [comment]
I tried to used Python3 latest version and it worked as well as centos

**Comment by christophetd** [comment]
Thanks, clarified in the README to use Python3 and suggested using a virtual env to avoid dependency issues
