### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by wicked-wick** [christophetd/CloudFlair#50]
I have dnspython correctly installed but it shows no module named dns.python?

**Comment by christophetd** [comment]
I updated the instructions in the README. Can you try the following and confirm it works fine?

```
cd cloudflair
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python cloudflair.py google.com
```

**Comment by christophetd** [comment]
Assuming this works now, feel free to reopen if needed!
