### ISSUE TITLE
ModuleNotFoundError: No module named 'html_similarity'

### ISSUE THREAD

**Issue by pedrobart** [christophetd/CloudFlair#56]
sudo python3 cloudflair.py   

[*] Retrieving Cloudflare IP ranges from https://www.cloudflare.com/ips-v4
Traceback (most recent call last):
  File "/home/bart/Tools/IP-Scan/CloudFlair/cloudflair.py", line 10, in <module>
    from html_similarity import similarity
ModuleNotFoundError: No module named 'html_similarity'

**Comment by christophetd** [comment]
Have you run the instructions?

```
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python cloudflair.py
```

**Comment by pedrobart** [comment]
> Have you run the instructions?
> 
> ```
> python3 -m venv venv
> source venv/bin/activate
> pip install -r requirements.txt
> python cloudflair.py
> ```

thank you, @christophetd
