### ISSUE TITLE
Expand timeout time

### ISSUE THREAD

**Issue by whydee86** [christophetd/CloudFlair#58]
There is an option to expand the timeout time to be more than 3 seconds?

![image](https://user-images.githubusercontent.com/43274863/160615200-f4a20e3a-9316-48f1-8c9e-0678145d2950.png)

**Comment by christophetd** [comment]
You should be able to customize it in the code here: https://github.com/christophetd/CloudFlair/blob/master/cloudflair.py#L17

No immediate plans to make it customizable from the CLI

**Comment by whydee86** [comment]
Thank you very much!
