### ISSUE TITLE
[*] Retrieving Cloudflare IP ranges from https://www.cloudflare.com/ips-v4

### ISSUE THREAD

**Issue by fdguyg8** [christophetd/CloudFlair#59]
i enter python cloudflair.py myvulnerable.site
`[*] Retrieving Cloudflare IP ranges from https://www.cloudflare.com/ips-v4
Traceback (most recent call last):
  File "/home/iu/cloudflair/cloudflair.py", line 4, in <module>
    import cloudflare_utils
  File "/home/iu/cloudflair/cloudflare_utils.py", line 47, in <module>
    cloudflare_subnets = [ipaddress.ip_network(ip_range) for ip_range in cloudflare_ip_ranges]
  File "/home/iu/cloudflair/cloudflare_utils.py", line 47, in <listcomp>
    cloudflare_subnets = [ipaddress.ip_network(ip_range) for ip_range in cloudflare_ip_ranges]
  File "/usr/lib/python3.9/ipaddress.py", line 83, in ip_network
    raise ValueError('%r does not appear to be an IPv4 or IPv6 network' %
ValueError: '<!DOCTYPE html>' does not appear to be an IPv4 or IPv6 network`

I've already completed pip install -r requirements.txt

**Comment by christophetd** [comment]
I just tried it, seems to be working for me:

```
$ python cloudflair.py medium.com
[*] Retrieving Cloudflare IP ranges from https://www.cloudflare.com/ips-v4
[*] The target appears to be behind CloudFlare.
[*] Looking for certificates matching "medium.com" using Censys
[*] 17 certificates matching "medium.com" found.
[*] Looking for IPv4 hosts presenting these certificates...
[*] 23 IPv4 hosts presenting a certificate issued to "medium.com" were found.
```

Is it possible CloudFlaire blocked your IP when requesting the list of IPs? Can you try this and let me know what you get?

``` 
curl -v https://www.cloudflare.com/ips-v4
```

**Comment by fdguyg8** [comment]
i do it curl -v https://www.cloudflare.com/ips-v4
`curl -v https://www.cloudflare.com/ips-v4                                                                                                                                                                                            1 ⨯
*   Trying 104.16.124.96:443...
* Connected to www.cloudflare.com (104.16.124.96) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=www.cloudflare.com
*  start date: Sep 18 00:00:00 2021 GMT
*  expire date: Sep 17 23:59:59 2022 GMT
*  subjectAltName: host "www.cloudflare.com" matched cert's "www.cloudflare.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x56478775a790)
> GET /ips-v4 HTTP/2
> Host: www.cloudflare.com
> user-agent: curl/7.81.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 403 
< date: Thu, 21 Apr 2022 18:15:12 GMT
< content-type: text/html; charset=UTF-8
< cf-chl-bypass: 1
< permissions-policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
< cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< expires: Thu, 01 Jan 1970 00:00:01 GMT
< x-frame-options: SAMEORIGIN
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< set-cookie: __cf_bm=8qMa15OJUAksVf_GeS450MXkBBXA35MrXeoLKazXhUA-1650564912-0-ATPovmbLZhxBdxaceLFanpw8uVE1+n43gLrpc+X+Vsgp7w0G0/rMHX0TxT4TDbOCT4N6i7VSmjFa8YQokaL28JL1vTi0xuqwNEPrlVuTHPs/; path=/; expires=Thu, 21-Apr-22 18:45:12 GMT; domain=.www.cloudflare.com; HttpOnly; Secure; SameSite=None
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=%2FJ%2FZtq87MOrEUdWVWs%2F82WnXMkuQ2v8Z6FSC54wDPD9qErW6j3qStp76yyr0hAubPgMrev3w4FFkfMdLLli5WNoXbuVil04RIUnu3lAZPDNiXCzpvp%2B7jRaiNAXtE%2FilwcJh6A%3D%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 6ff81a8d3eeb6904-FRA
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
< 
<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>

<title>Please Wait... | Cloudflare</title>
  
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />

<style>body{margin:0;padding:0}</style>



<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>



  
    <script>
    //<![CDATA[
    (function(){
      window._cf_chl_opt={
        cvId: "2",
        cType: "managed",
        cNounce: "6455",
        cRay: "6ff81a8d3eeb6904",
        cHash: "96ba0f721f1e540",
        cUPMDTk: "\/ips-v4?__cf_chl_tk=jVb3PaFlxy5Z4jOxB40iK96CWXY9IkKZnyiTMmKg.pI-1650564912-0-gaNycGzNB1E",
        cFPWv: "g",
        cTTimeMs: "1000",
        cLt: "n",
        cRq: {
          ru: "aHR0cHM6Ly93d3cuY2xvdWRmbGFyZS5jb20vaXBzLXY0",
          ra: "Y3VybC83LjgxLjA=",
          rm: "R0VU",
          d: "XiAv6l1MNllV2F8SHiJoTJn+qwvMn4GMDZrTG5qHyShpgECd+Wvrz1H5kxEp9hhhnsXAgWcRovYCUidFpV5NONfmz6RAcpv/a3NkfgVICJrPNWL7EHzkuTmWTJfOeCLBFh2M4+vBPkkWjVCr6dNrJflZhAljLaOW7/eTLbEiNcuNhGDyXYz5tIFfjoD2X+9j+iKge9pRhX9iYjtYWRVTvjAqIUVccngmQBrPH4qJkha+2oHOwV6yXuRHlujh7pFC1TwcwBKf0qzNPO3apsQAEX4guNywkpVmcz2s90JSvzKmm3Hxi//TOhM9uiBcV938TPi7QaA7R7DwmRfL5xIF0Cklu8l1MbrIESjwFkTDxBgvfg5hu4v3ePBj2rW4y9V10/p1RJ5kf2dpwCyctWQXdOeOaY2zZ13yUzPjh+njJ0Zfr55Twz2zESmHItL5XpH7pW9OLDwCCwFIkeKoy8gOaGrNv3bh4u/tTQSIm9ppS9w6cWmCzZu9tot5fUBo3gmg0hnvnCDzpL3kHqMoJQxf5c/DYqWsHXhbw1ieQ3UtpdWz/xq0tp7BT50fwH9rIqQQqig26vaP+/Tj+6hmaYNZkg==",
          t: "MTY1MDU2NDkxMi4yMTMwMDA=",
          m: "qXADJ4mWqGGlH6Ol69BIFdiIeRHYQ17SLHK8ZiwkxcQ=",
          i1: "3dS+bKxS9A69F46+dZACVA==",
          i2: "ecUZdUzDaj2dguQN6eleYg==",
          zh: "WknVD3gDHQEGTLPKhwAHV9fbqA3BzTCoGSgrSa52xC0=",
          uh: "XtPohTwN9ruoNwJrCbocmA5soW1XPnkxU/yVFmBLOQo=",
          hh: "o2CsT6J8k5XABFTKG8Pc+kjAUTbm0LrSlAwXOrIi85c=",
        }
      };
    }());
    //]]>
    </script>
  

<style>
  #cf-wrapper #spinner {width:69px; margin:  auto;}
  #cf-wrapper #cf-please-wait{text-align:center}
  .attribution {margin-top: 32px;}
  .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
  #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
  #cf-hcaptcha-container { text-align:center;}
  #cf-hcaptcha-container iframe { display: inline-block;}
  @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
  #cf-wrapper #cf-bubbles { width:69px; }
  @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
  #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
  #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
  #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
</style>
</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
      
        <h1 data-translate="managed_challenge_headline">Please wait...</h1>
        <h2 class="cf-subheadline"><span data-translate="managed_checking_msg">We are checking your browser...</span> www.cloudflare.com</h2>
      
      </div>
      
      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
            
              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form managed-form" id="challenge-form" action="/ips-v4?__cf_chl_f_tk=jVb3PaFlxy5Z4jOxB40iK96CWXY9IkKZnyiTMmKg.pI-1650564912-0-gaNycGzNB1E" method="POST" enctype="application/x-www-form-urlencoded">
  
    <div id='cf-please-wait'>
      <div id='spinner'>
        <div id="cf-bubbles">
            <div class="bubbles"></div>
            <div class="bubbles"></div>
            <div class="bubbles"></div>
        </div>
      </div>
      <p data-translate="please_wait" id="cf-spinner-please-wait">Please stand by, while we are checking your browser...</p>
      <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting...</p>
      </div>
  
  <input type="hidden" name="md" value="u6RSDAOwe3KUZd.2s5Z11eHRQ1cS2HcU1lWaBIt_kU0-1650564912-0-ARkPn6tsrH09g0iwMF5IBisPvxue4iAbTYYHz1EuXSyPrKdvYy4OVOUpOd_7U5zVEiXLFcEP5p4Y-IH8RDOUwZrCJukTg0tj9uDMAaf3haQKkqrYnbmfkNzLmQ86Y-M7GnoTyPihcwU5r8VkSK5lhvz1iRZG704FxNpUz7nUULqY_z_wFdJcZkptBbsONq4u8Hg7OgY7uC45fogQ4VqboYAh4XkZ1gltdlIhj0Efiv7tklvJ1HR5b8EvW9z05Hpnk5VtYrWabEmZ4-a0APab3x44HtizFvG-551j5YcPVWnu0XlK_Vy1Tudy-5_qcETqvhgxni9vimlUhbTZwcXC54HBFHa8pZf9C98XcOloLcAtM6W0qqiG4JY2IwbrUnYS5GiYUMM1sJVEoCV-Nzob5DCkOT-iS7JNIW2M07RBdZXUwXtmEelx_g-KitnKYLpd49e_tvWC9wAU48-mhRnq6TrZyld4gHzfD0DNG40rub6I0mqTyHyM6LDjpyF2A_xnH7r6vLfjaw4sus1SaiNwRAV1y8Tb1dAFKUkNvtKs6SeovinSuYis-V_c_eItiTdlHtJDCNoYeaPqni2VsNaEOyZVHcRJLvj9rDANk2FlnTjkiLL5dymqkf6cHGi7sRYQ5Kzoyn43rQlatqa11gi_7THcoaeoPQd7ZHdXyJ0vUoNYvHdVZUcX_sOFAfC9lpKpHVQ8-MSIHGUOSPqbjTf-UVn8HPoK8pLKutCe4GOJUh1io8Iv_okg5yBSJiqUZsKaiPnMxkWr77iS3LNKdrdi0V7pW5UPizACY7DjvGJ3rdDR" />
  <input type="hidden" name="r" value="C7bkXKePM8ywJidA3Kxk3WlZKUnbiHNvcP3aRHlOYj8-1650564912-0-AQ8yPUkkZAcy5ei3m1/900m/MsinIxmpZoU0uKuRBShQy6ibiC7+4RbtAUbhETV+Wik3E5DLLSHXzrfurmbo88QY+CTuKSiDC1Zp3eL4IxJQSt9+QlXN57xO9+q4fZv940pNKEGAN6bTw++R1O539qfL5lw3+qn/+X598pte5zjmReVAz+R8sDiIJCxnBcJSDXO7Ba/ZN8S0whiqDj9P6UyIeDboUN6ALkG6f7mgAkeOcimXbA1CQPKBleZQNwIFRV46z5xyDefm59knQH1FGL9sgUNCgsBj0TwO3C2NpSJLJzuvMFWuztNUpHPYEaTiH3EmMf8Dd7GHIVFp7dWqDY6COsCvIMKKFHTiDvgnwqBHOI7RNR1/xeG4luNEiZ0Pn+WUiwVyLCZEFOsnTDG6JUWVbI0e74wOFqPKHBB1bOcMcpH93G5PSJ3ckXAMGtiX8AUkK6XDBGeDug3CgcAp/Xcq5Koqk5LVcXxWg9N9xY+QEo/C9ZTPYlAGlizq2i0cjhJIfh7cTPU0O8WGTHZ93MGrfI/3E6lFubc7VmbWsRMHavvs1KsfEBfdPmHF0aQPKDZEMNG0fjGTQasvMgiiKrZ1qImLSFT4g4kBbHIErbEPtz/QiwEZsRia/1LMHrj9yHTP2me06UZ1KzsO364sF9vwzmELT0HEMGWlaQQRA9SEg1K+NC/4sMIvDR6PZ/G1LAPE9aigy4ajcWgdVIzafRv20vInPbdvgIOZS+qhE6vqd/1wwnO8C5GWqjYPIDnLX6lon9PmJa+2MsPCW5B/mSFQrQ99ejj0DK7Th8Md4aO/LR3JwbqojlXvLYorBa6RcpdCfUJ9ZCIvveJJCViNthhlIvzMsoiTAoKB+I63p0ZePIvqTnAa6bstx5kD+H+t2eNkUiJSVRZ9aMqI4WXDajhGueyCqg/WdPaU88IGLqeZJ1/ES4sqlVB4Fg10DmiHOtjlU5rUaOPawK0L+526p85IiWp20oAEEAcbHKlF8CxPQ+uP1qDgxc23z5m6P6dagK5NwLHH2s/xW4O/6qdtmd241A3aCy+D04e6Olqck55vBr1OZHNXQJY3Y5p5m9iWDQJo+0vzN7ceeSzExDymmdDAYztZLGiULDcvOGmoMvJZ58unn/FDCGbFPrfBGnRjV0Xsfh7k98lcrrVvofOtqvotS+P5sAupR8Y3rtyUAwi6lt1PpXn+bQQLYzHz6ek5REDltODGRv29kSyM8io9thv/YCZzwgrClEwafptx5sF/3r/9J7FgTpxowYEnfAyIynNmaSxEbr9qoSmKTlFlaEVaK/893UxtkZSqoxC+0tbroqx6ufCHsJ9m6Hl9LNb+7Sk00bg0SvVZF/SPXhn1VPp7OaF2Kdin8m0LVDIE+/LXWiGepkITWqrUONszf+NKmCJGmNoaiaM/HNhvZwDkD2P75+UBSGfRZ49/Jl8QoA792Gy5egWRh3GGpQV2oygFbCnhcBAkncQM6wcHa6dTUxb6y6oMzdU7qqcDqD7XBRBRB324x1KA3JWkTRtG1QZ6LGE7LWmulgdO95EHTJzbWkT47cNUmKQb4Tj+TTLT0TGX3VBDcT7kSdAB1yFLhEB1m4qYZt6KKs4Ebiw36uR2po6wVxGLnWdzz56k/WUnq3n/ZuGoxGDXAOCTfIAPaMKYAaoyPzhT62TyDV5EtH6UA5SjlVeYCkJ+Vw255u4x2mbUcaydFofV/4MLfN1wgU9TNI8dyMalSaBOq6SdRntGcaLQi0U0S7C1aRRXVnbNMDHdIowXTQhXtYepQ0rpm7HsF5Y1Vecm15LUmm9prJUNgY4=">
  <input type="hidden" name="vc" value="ea6f7cf5eb6bbb370198fddc44d33056">
  
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
  <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
  <script>
  //<![CDATA[
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
      b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
      b(function(){
        var cookiesEnabled=(navigator.cookieEnabled)? true : false;
        if(!cookiesEnabled){
          var q = document.getElementById('no-cookie-warning');q.style.display = 'block';
        }
      });
  //]]>
  </script>
  <div id="trk_captcha_js" style="background-image:url('/cdn-cgi/images/trace/captcha/nojs/h/transparent.gif?ray=6ff81a8d3eeb6904')"></div>
</form>
  
  <script>
    //<![CDATA[
    (function(){
        var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);
        var trkjs = isIE ? new Image() : document.createElement('img');
        trkjs.setAttribute("src", "/cdn-cgi/images/trace/managed/js/transparent.gif?ray=6ff81a8d3eeb6904");
        trkjs.id = "trk_managed_js";
        trkjs.setAttribute("alt", "");
        document.body.appendChild(trkjs);
        var cpo=document.createElement('script');
        cpo.type='text/javascript';
        cpo.src="/cdn-cgi/challenge-platform/h/g/orchestrate/managed/v1?ray=6ff81a8d3eeb6904";
        
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.indexOf('?') !== -1 ? '?' : location.search;
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        if (window._cf_chl_opt.cUPMDTk && window.history && window.history.replaceState) {
          var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
          history.replaceState(null, null, "\/ips-v4?__cf_chl_rt_tk=jVb3PaFlxy5Z4jOxB40iK96CWXY9IkKZnyiTMmKg.pI-1650564912-0-gaNycGzNB1E" + window._cf_chl_opt.cOgUHash);
          cpo.onload = function() {
            history.replaceState(null, null, ogU);
          };
        }
        
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
    //]]>
    </script>
  


              </div>
            </div>

            <div class="cf-column">
              <div class="cf-screenshot-container">
              
                <span class="cf-no-screenshot"></span>
              
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>
            
            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>
            

            <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

            <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>
            
              
            
          </div>
        </div>
      </div>
      

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">6ff81a8d3eeb6904</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 109.70.100.23</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div>


    </div>
  </div>

  <script>
  window._cf_translation = {};
  
  
</script>


</body>
</html>
* Connection #0 to host www.cloudflare.com left intact`
but still knocks out 
`[*] Retrieving Cloudflare IP ranges from https://www.cloudflare.com/ips-v4
Traceback (most recent call last):
  File "/home/iu/.local/share/Trash/files/cloudflair.2/cloudflair/cloudflair.py", line 4, in <module>
    import cloudflare_utils
  File "/home/iu/.local/share/Trash/files/cloudflair.2/cloudflair/cloudflare_utils.py", line 47, in <module>
    cloudflare_subnets = [ipaddress.ip_network(ip_range) for ip_range in cloudflare_ip_ranges]
  File "/home/iu/.local/share/Trash/files/cloudflair.2/cloudflair/cloudflare_utils.py", line 47, in <listcomp>
    cloudflare_subnets = [ipaddress.ip_network(ip_range) for ip_range in cloudflare_ip_ranges]
  File "/usr/lib/python3.9/ipaddress.py", line 83, in ip_network
    raise ValueError('%r does not appear to be an IPv4 or IPv6 network' %
ValueError: '<!DOCTYPE html>' does not appear to be an IPv4 or IPv6 network
`

**Comment by fdguyg8** [comment]
i run commands with ip tor
here's what gave me
`[*] Retrieving Cloudflare IP ranges from https://www.cloudflare.com/ips-v4
Traceback (most recent call last):
  File "/home/iu/.local/share/Trash/files/cloudflair.2/cloudflair/cloudflair.py", line 4, in <module>
    import cloudflare_utils
  File "/home/iu/.local/share/Trash/files/cloudflair.2/cloudflair/cloudflare_utils.py", line 47, in <module>
    cloudflare_subnets = [ipaddress.ip_network(ip_range) for ip_range in cloudflare_ip_ranges]
  File "/home/iu/.local/share/Trash/files/cloudflair.2/cloudflair/cloudflare_utils.py", line 47, in <listcomp>
    cloudflare_subnets = [ipaddress.ip_network(ip_range) for ip_range in cloudflare_ip_ranges]
  File "/usr/lib/python3.9/ipaddress.py", line 83, in ip_network
    raise ValueError('%r does not appear to be an IPv4 or IPv6 network' %
ValueError: '<!DOCTYPE html>' does not appear to be an IPv4 or IPv6 network
`

**Comment by christophetd** [comment]
CloudFlare is blocking your IPs, so you can't retrieve its list of IPs.

I recommend either using another IP, or copy-pasting:

```
173.245.48.0/20
103.21.244.0/22
103.22.200.0/22
103.31.4.0/22
141.101.64.0/18
108.162.192.0/18
190.93.240.0/20
188.114.96.0/20
197.234.240.0/22
198.41.128.0/17
162.158.0.0/15
104.16.0.0/13
104.24.0.0/14
172.64.0.0/13
131.0.72.0/22
````

Instead of this function call: https://github.com/christophetd/CloudFlair/blob/dce0488f2fe5a82334e0d7fbf26c580430aae1e5/cloudflare_utils.py#L42

**Comment by fdguyg8** [comment]
changed ip all worked
