### ISSUE TITLE
ModuleNotFoundError: No module named 'censys'

### ISSUE THREAD

**Issue by apprahuman** [christophetd/CloudFlair#65]
[*] Retrieving Cloudflare IP ranges from https://www.cloudflare.com/ips-v4
Traceback (most recent call last):
  File "cloudflair.py", line 7, in <module>
    import censys_search
  File "/Users/mohamedrahuman/bugbountry/tools/wafBypass/cloudflair/censys_search.py", line 3, in <module>
    from censys.common import __version__
ModuleNotFoundError: No module named 'censys'

Getting above error when trying to run this tool.
Tried to install the packages but still same error.

I am using MacOS Montery

Any tip, still googling to fix this. This tools seems cool, really want it work for me, thanks

**Comment by christophetd** [comment]
Hello,

Did you install the dependencies?

```
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt

# When you're done:
deactivate
```

**Comment by apprahuman** [comment]
I have run source venv/bin/activate then it' works. Thanks
