### ISSUE TITLE
ImportError: No module named dns.resolver

### ISSUE THREAD

**Issue by arrmani88** [christophetd/CloudFlair#72]
First of all thank you for this wornderful tool.
after following the docs, and running `python cloudflair.py exampledomain.name` i got the following error message: 
```
Traceback (most recent call last):
  File "cloudflair.py", line 3, in <module>
    import dns_utils
  File "/Users/anel-bou/Desktop/CloudFlair/dns_utils.py", line 1, in <module>
    import dns.resolver
ImportError: No module named dns.resolver
```
running on MacOs Catalina (`zsh`), and Python 2.7.16

**Comment by christophetd** [comment]
c.f. https://github.com/christophetd/CloudFlair#compatibility, only Python 3.6+ is supported. Can you try again using a more recent version of Python?
