### ISSUE TITLE
Bad Pattern Error

### ISSUE THREAD

**Issue by lumideez** [christophetd/CloudFlair#78]
please I keep getting bad pattern error when attempting to scan my site..

my command is this 

cloudflair.py [-h] [--output None] [--censys-api-id f4b4663a-d6b0-4be2-b146-91f52fdxxxx] [--censys-api-secret LQSzw5s68kiQyZq8REnyZbHBc1xxxx] [--cloudfront False] mysite.com

Am I missing something?

**Comment by christophetd** [comment]
Hi, 

What's the exact error you're getting?

**Comment by lumideez** [comment]
Thank you for your response. The error shown was 

zsh: bad pattern: [--output

**Comment by christophetd** [comment]
You need to use

```
cloudflair.py --censys-api-id f4b4663a-d6b0-4be2-b146-91f52fdxxxx] --censys-api-secret LQSzw5s68kiQyZq8REnyZbHBc1xxx mysite.com
```
